começo da database
grabsks/uLift-API pull request #13
Opened 2020-03-07 22:51 UTC by Hermes-Francisco

instalei o sequelize

2020-03-07 23:01 UTC, GuilhermehChaves requested changes
Mudar nome do arquivo connection.js para index.js

2020-03-07 23:01 UTC, GuilhermehChaves commented on helper/db/connection.js
> +
Remover quebra de linha

2020-03-07 23:01 UTC, GuilhermehChaves commented on helper/db/connection.js
> +
Remover quebra de linha

2020-03-08 00:34 UTC, GuilhermehChaves commented on helper/db/connection.js
> +    Connect(){
Alterar connect para letra minúscula

2020-03-08 18:21 UTC, Hermes-Francisco commented
já mudei o nome do arquivo connection.js para index.js. eu preciso mudar o nome da classe database também?

2020-03-09 00:45 UTC, GuilhermehChaves approved these changes

2020-03-09 22:01 UTC, YuriAsthar approved these changes

2020-03-09 22:01 UTC, merged