Criando Models de User e College
grabsks/uLift-API pull request #23
Opened 2020-03-10 04:33 UTC by GuilhermehChaves

2020-03-11 00:19 UTC, luanfonsecap reviewed
no model college não seria necessário o nome da instituição também ?

2020-03-12 00:26 UTC, luanfonsecap approved these changes

2020-03-12 00:45 UTC, grabsks requested changes

2020-03-12 00:45 UTC, GrabK5 commented on helper/db/index.js
> +const models = [User, College];
! kkkkkk

2020-03-12 01:16 UTC, grabsks approved these changes

2020-03-12 01:16 UTC, merged