Create user
grabsks/uLift-API pull request #34
Opened 2020-03-21 23:24 UTC by Hermes-Francisco

criei o UserController e corrigi a migration do user

2020-03-22 13:41 UTC, luanfonsecap requested changes

2020-03-22 13:41 UTC, luanfonsecap commented on controller/UserController.js
> +    if(check)return response.status(400).json({error: "Usuário já cadastrado"});
Não seria mais corre o status 200 ? Pois não foi um erro em si do cliente, uma requisição mal feita, foram dados que ele pretendia cadastrar mas não estão disponíveis. Normalmente 400 é para uma requisição inválida.

A própria Google utiliza 200 nesses casos: 
![Captura de tela de 2020-03-22 10-37-10](https://user-images.githubusercontent.com/43269295/77250826-33fe8a80-6c29-11ea-99ec-fd4daca0150a.png)

2020-03-22 13:47 UTC, GuilhermehChaves requested changes

2020-03-22 13:47 UTC, GuilhermehChaves commented on controller/UserController.js
> +    const check = await User.findOne({
Podia mudar a constante `check` para `userExists`, o nome check não é muito descritivo, oque você ta checando?

2020-03-22 13:47 UTC, GuilhermehChaves commented on controller/UserController.js
> +    const {ra, name, email} = await User.create(request.body);
Recuperar o id aqui também

2020-03-22 13:47 UTC, GuilhermehChaves commented on controller/UserController.js
> +    return response.status(201).json({ra, name, email});
Enviar o id na resposta.

2020-03-22 14:00 UTC, luanfonsecap commented on controller/UserController.js
> +    return response.status(201).json({ra, name, email});
Pode até enviar a resposta completa do Sequelize, com todos os dados de criação do usuário

2020-03-22 14:05 UTC, GuilhermehChaves commented on controller/UserController.js
> +    return response.status(201).json({ra, name, email});
Na verdade a senha não precisa

2020-03-22 17:18 UTC, luanfonsecap approved these changes

2020-03-23 15:43 UTC, GuilhermehChaves approved these changes

2020-03-23 18:07 UTC, merged